// --------------------------------------------------------------------------------------------------------------------
// <copyright file="AuthorizationSource.cs" company="Naos">
//   Copyright (c) Naos 2018. All rights reserved.
// </copyright>
// <auto-generated>
//   Sourced from NuGet package. Will be overwritten with package update except in Naos.Recipes.Api.SelfHost.Bootstrapper.Common source.
// </auto-generated>
// --------------------------------------------------------------------------------------------------------------------

namespace $rootnamespace$
{
    /// <summary>
    ///     Set of all possible authorization sources.
    /// </summary>
    public enum AuthorizationSource
    {
        /// <summary>
        /// Header based authorization.
        /// </summary>
        Header = 0,

        /// <summary>
        /// Form based authorization.
        /// </summary>
        Form,

        /// <summary>
        /// Query string based authorization.
        /// </summary>
        QueryString,
    }
}