// --------------------------------------------------------------------------------------------------------------------
// <copyright file="DefaultExceptionLogger.cs" company="Naos">
//   Copyright (c) Naos 2018. All rights reserved.
// </copyright>
// <auto-generated>
//   Sourced from NuGet package. Will be overwritten with package update except in Naos.Recipes.Api.SelfHost.Bootstrapper.Common source.
// </auto-generated>
// --------------------------------------------------------------------------------------------------------------------

namespace $rootnamespace$
{
    using System.Web.Http.ExceptionHandling;

    using OBeautifulCode.Validation.Recipes;

    /// <summary>
    /// Logs all Web API exceptions.
    /// </summary>
    /// <seealso cref="System.Web.Http.ExceptionHandling.ExceptionLogger" />
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [System.CodeDom.Compiler.GeneratedCode("Naos.Recipes.Api.SelfHost.Bootstrapper.Common", "See package version number")]
    public class DefaultExceptionLogger : ExceptionLogger
    {
        /// <summary>
        /// Logs the exception synchronously.
        /// </summary>
        /// <param name="context">The exception logger context.</param>
        public override void Log(ExceptionLoggerContext context)
        {
            new { context }.Must().NotBeNull();

            Its.Log.Instrumentation.Log.Write(context.Exception);
        }
    }
}