// --------------------------------------------------------------------------------------------------------------------
// <copyright file="FileCertificateFetcher.cs" company="Naos">
//   Copyright (c) Naos 2018. All rights reserved.
// </copyright>
// <auto-generated>
//   Sourced from NuGet package. Will be overwritten with package update except in Naos.Recipes.Api.SelfHost.Bootstrapper.Common source.
// </auto-generated>
// --------------------------------------------------------------------------------------------------------------------

namespace $rootnamespace$
{
    using System;
    using System.Security.Cryptography.X509Certificates;

    /// <summary>
    /// Fetches certificates from files.
    /// </summary>
    /// <seealso cref="ICertificateFetcher"/>
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [System.CodeDom.Compiler.GeneratedCode("Naos.Recipes.Api.SelfHost.Bootstrapper.Common", "See package version number")]
    public class FileCertificateFetcher : ICertificateFetcher
    {
        private readonly RelativeFileCertificate fileCertificate;

        /// <summary>
        /// Initializes a new instance of the <see cref="FileCertificateFetcher"/> class.
        /// </summary>
        /// <param name="fileCertificate">The file certificate.</param>
        /// <exception cref="System.ArgumentNullException">If any arguments are null.</exception>
        public FileCertificateFetcher(RelativeFileCertificate fileCertificate)
        {
            this.fileCertificate = fileCertificate ?? throw new ArgumentNullException(nameof(fileCertificate));
        }

        /// <summary>
        /// Fetches a certificate.
        /// </summary>
        /// <returns>The certificate.</returns>
        public X509Certificate2 Fetch()
        {
            var certificate = new X509Certificate2(
                this.fileCertificate.FilePath,
                this.fileCertificate.Password,
                this.fileCertificate.KeyStorageFlags);

            return certificate;
        }
    }
}