// --------------------------------------------------------------------------------------------------------------------
// <copyright file="HarnessSettings.cs" company="Naos">
//   Copyright (c) Naos 2018. All rights reserved.
// </copyright>
// <auto-generated>
//   Sourced from NuGet package. Will be overwritten with package update except in Naos.Recipes.Api.SelfHost.Bootstrapper.Common source.
// </auto-generated>
// --------------------------------------------------------------------------------------------------------------------

namespace $rootnamespace$
{
    using System;

    /// <summary>
    /// Object representing the harness settings.
    /// </summary>
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [System.CodeDom.Compiler.GeneratedCode("Naos.Recipes.Api.SelfHost.Bootstrapper.Common", "See package version number")]
    public class HarnessSettings
    {
        /// <summary>
        /// Gets or sets the time to live (will not be honored until active connections are finished processing).
        /// </summary>
        public TimeSpan TimeToLive { get; set; }

        /// <summary>
        /// Gets or sets the interval to poll for completion.
        /// </summary>
        public TimeSpan PollingInterval { get; set; }
    }
}