// --------------------------------------------------------------------------------------------------------------------
// <copyright file="HostingSettings.cs" company="Naos">
//   Copyright (c) Naos 2018. All rights reserved.
// </copyright>
// <auto-generated>
//   Sourced from NuGet package. Will be overwritten with package update except in Naos.Recipes.Api.SelfHost.Bootstrapper.Common source.
// </auto-generated>
// --------------------------------------------------------------------------------------------------------------------

namespace $rootnamespace$
{
    using System.Collections.Generic;

    /// <summary>
    /// Object representing the hosting settings.
    /// </summary>
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [System.CodeDom.Compiler.GeneratedCode("Naos.Recipes.Api.SelfHost.Bootstrapper.Common", "See package version number")]
    public class HostingSettings
    {
        /// <summary>
        /// Gets the URLs.
        /// </summary>
        /// <value>The URL.</value>
        public ICollection<string> Urls { get; } = new List<string>();

        /// <summary>
        /// Gets or sets the CORS settings instance.
        /// </summary>
        /// <value>
        /// The CORS settings instance.
        /// </value>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Cors", Justification = "Spelling/name is correct.")]
        public Cors Cors { get; set; }
    }
}