// --------------------------------------------------------------------------------------------------------------------
// <copyright file="JwtAuthenticationSettings.cs" company="Naos">
//   Copyright (c) Naos 2018. All rights reserved.
// </copyright>
// <auto-generated>
//   Sourced from NuGet package. Will be overwritten with package update except in Naos.Recipes.Api.SelfHost.Bootstrapper.Common source.
// </auto-generated>
// --------------------------------------------------------------------------------------------------------------------

namespace $rootnamespace$
{
    using System.Collections.Generic;
    using System.Diagnostics.CodeAnalysis;

    /// <summary>
    /// Provides settings for a JWT authentication client.
    /// </summary>
    [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Jwt", Justification = "Spelling/name is correct.")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [System.CodeDom.Compiler.GeneratedCode("Naos.Recipes.Api.SelfHost.Bootstrapper.Common", "See package version number")]
    public class JwtAuthenticationSettings
    {
        /// <summary>
        /// Gets or sets the allowed clients.
        /// </summary>
        /// <value>The allowed clients.</value>
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Justification =
            "This is designed for serialization and deserialization to and from JSON which needs to be able to set this property.")]
        public ICollection<string> AllowedClients { get; set; } = new List<string>();

        /// <summary>
        /// Gets or sets the allowed servers.
        /// </summary>
        /// <value>The allowed servers.</value>
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Justification =
            "This is designed for serialization and deserialization to and from JSON which needs to be able to set this property.")]
        public ICollection<JwtAuthenticationServer> AllowedServers { get; set; } = new List<JwtAuthenticationServer>();

        /// <summary>
        /// Gets or sets the relative file certificate.
        /// </summary>
        /// <value>The relative file certificate.</value>
        public RelativeFileCertificate RelativeFileCertificate { get; set; }

        /// <summary>
        /// Gets or sets the store certificate.
        /// </summary>
        /// <value>The store certificate.</value>
        public StoreCertificate StoreCertificate { get; set; }

        /// <summary>
        /// Gets or sets the authorization key for form or query string values.
        /// </summary>
        /// <value>
        /// The authorization key for form or query string values.
        /// </value>
        public string AuthorizationKey { get; set; }

        /// <summary>
        /// Gets the authorization priority.
        /// </summary>
        /// <value>
        /// The authorization priority.
        /// </value>
        public ICollection<AuthorizationSource> AuthorizationPriority { get; } = new List<AuthorizationSource>();
    }
}